// KineticScrolling
// https://code.google.com/p/kineticscrolling/
// Copyright (c) 2010 Tatsuhiro Tsujikawa
// Released under the MIT License
var g=null;function i(){this.a=g;this.b=[];this.c=this.i=this.j=this.m=this.g=this.d=g;this.e=new KineticScrollingOverlay_;this.h=5.0E-5;this.k=50}function k(a,b){return Math.sqrt(b[0]*b[0]+b[1]*b[1])}function n(a,b,e,c,f,d,o,p){function m(h){var l=(new Date).getTime();if(!(l-h>a.k*3)){h=l-p;var j=h*h;h=b-c*j;j=f-o*j;if(h>1||j>1){a.a.panBy(h*e,j*d);a.d=window.setTimeout(function(){m(l)},a.k)}}}return m}
function q(a){return function(){a.d&&window.clearTimeout(a.d);a.c=google.maps.event.addListener(a.a,"mousemove",r(a));a.b=[]}}
function s(a){return function(){google.maps.event.removeListener(a.c);a.c=g;if(!(a.b.length<2)){for(var b=a.b[0].l,e=a.b[0].f,c=g,f=g,d=1;d<a.b.length;++d){if(e-a.b[d].f>200)break;c=a.b[d].l;f=a.b[d].f}if(c)if(e!=f){b=[b.x-c.x,b.y-c.y];d=k(a,b);if(d!=0){c=[1,0];c=Math.acos((b[0]*c[0]+b[1]*c[1])/(k(a,b)*k(a,c)));e=Math.min(40,d/(e-f)*30);f=Math.cos(c);c=Math.sin(c);d=(new Date).getTime();n(a,Math.abs(f)*e,b[0]<0?1:-1,Math.abs(f*a.h),Math.abs(c)*e,b[1]<0?1:-1,Math.abs(c*a.h),d)(d)}}}}}
function r(a){return function(b){a.b.unshift({l:a.e.getProjection().fromLatLngToContainerPixel(b.latLng),f:(new Date).getTime()});a.b.length>100&&a.b.pop()}}
i.prototype.setMap=function(a){if(this.a!=a){var b=this,e=function(){b.d&&window.clearTimeout(b.d)};if(this.a){google.maps.event.removeListener(this.g);google.maps.event.removeListener(this.m);google.maps.event.removeListener(this.j);google.maps.event.removeListener(this.i);this.c&&google.maps.event.removeListener(this.c);this.e.setMap(g);e()}if(this.a=a){this.e.setMap(this.a);this.g=google.maps.event.addListener(this.a,"click",e);this.m=google.maps.event.addListener(this.a,"zoom_changed",e);this.j=
google.maps.event.addListener(this.a,"dragstart",q(this));this.i=google.maps.event.addListener(this.a,"dragend",s(this))}}};i.prototype.getMap=function(){return this.a};function KineticScrollingOverlay_(){}KineticScrollingOverlay_.prototype=new google.maps.OverlayView;KineticScrollingOverlay_.prototype.onAdd=function(){};KineticScrollingOverlay_.prototype.draw=function(){};KineticScrollingOverlay_.prototype.onRemove=function(){};window.KineticScrolling=i;i.prototype.getMap=i.prototype.getMap;
i.prototype.setMap=i.prototype.setMap;window.KineticScrollingOverlay_=KineticScrollingOverlay_;KineticScrollingOverlay_.onAdd=KineticScrollingOverlay_.prototype.onAdd;KineticScrollingOverlay_.draw=KineticScrollingOverlay_.prototype.draw;KineticScrollingOverlay_.onRemove=KineticScrollingOverlay_.prototype.onRemove;
